### ISSUE TITLE
Does it work for T2 brain images?

### ISSUE THREAD

**Issue by ilyanelken** [iitzco/deepbrain#7]

**Comment by ilyanelken** [comment]
Also, is it possible to perform segmentation for a single 2D slice and not 3D niftii volume?

**Comment by olinickalls** [comment]
It doesn't work for T2 or T2 FLAIR.  It does seem to work quite well for SWI/SWAN interestingly, not that I can think of a good reason why you would want to...
I too want a good T2 or FLAIR model, though I will likely make assumptions about the patient not having moved and simply apply the T1 volume mask to the T2 FLAIR and T2 volumes.  The headache will be if the voxels are not the same size.

I haven't tried but I doubt it will work for single slices.  You'd probably have to extract the corresponding slice from the masked volume.

**Comment by ilyanelken** [comment]
@olinickalls I understand, thanks!
